{% set name = "Chameleon" %}
{% set version = "3.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Chameleon-{{ version }}.tar.gz
  sha256: 52e0922702798486419c4d8bcb7d0b9d3e0629ee305c459180c688eb03ba445f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - chameleon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://chameleon.readthedocs.io
  summary: Fast HTML/XML Template Compiler.
  license: BSD-4-Clause 
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ReimarBauer
